(()=>{'use strict';const form=document.getElementById('discovery'),panels=[...form.querySelectorAll('.panel')],next=document.getElementById('next'),previous=document.getElementById('previous'),error=document.getElementById('error');let step=0,busy=false;const t=s=>window.bbdTranslate?.(s)||s;
function render(){panels.forEach((p,i)=>p.hidden=i!==step);document.querySelectorAll('.step-indicator').forEach((p,i)=>{if(i===step)p.setAttribute('aria-current','step');else p.removeAttribute('aria-current')});previous.hidden=step===0;next.textContent=t(step===3?'Send questionnaire':'Continue')}
function validate(){for(const el of form.querySelectorAll('[required]'))if(!el.checkValidity()){step=0;render();el.focus();el.reportValidity();return false}return true}
previous.addEventListener('click',()=>{if(!busy){step--;render();panels[step].querySelector('h2').scrollIntoView({behavior:'smooth',block:'start'})}});
form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!validate())return;if(step<3){step++;render();panels[step].querySelector('h2').scrollIntoView({behavior:'smooth',block:'start'});return}busy=true;next.disabled=true;previous.disabled=true;next.textContent=t('Sending…');error.hidden=true;
const val=id=>document.getElementById(id).value.trim();const answers=Array.from({length:20},(_,i)=>({question:panels[Math.floor(i/5)].querySelectorAll('.question span')[i%5].textContent,answer:val('answer-'+(i+1))}));
const payload={company:val('company'),contact:val('contact'),email:val('email'),phone:val('phone'),business:val('answer-4'),audience:val('answer-2'),goal:val('answer-1'),style:val('answer-7'),inspiration:val('answer-8'),photos:val('answer-12'),services:val('answer-3'),timing:val('answer-19'),pages:['Home','About','Services','Portfolio','Process','Contact'],notes:'KPLAY USA — Website Discovery\n'+answers.map(a=>a.question+'\n'+(a.answer||'(No answer)')).join('\n\n')};
try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);let r;try{r=await fetch('https://built-by-davila-backend.onrender.com/prospect-api/intakes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal})}finally{clearTimeout(timer)}const result=await r.json().catch(()=>({}));if(!r.ok||!result.id)throw Error();form.hidden=true;document.querySelector('.progress').hidden=true;const done=document.getElementById('success');done.hidden=false;done.focus();}
catch{error.textContent=t('We could not confirm receipt. Your answers are still here. Please try again.');error.hidden=false;busy=false;next.disabled=false;previous.disabled=false;render()}});render();
})();
